{{- if .Values.postgres.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgres.app.name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
