apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vault.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.vault.app.name }} 
spec:
  replicas: {{ .Values.vault.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.vault.app.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.vault.app.name }} 
    spec:
{{- if .Values.vault.serviceAccount.create }}
      serviceAccountName: {{ .Values.vault.app.name }}-serviceaccount
{{- end }}
      containers:
      - name: {{ .Values.vault.app.name }}
        image: hashicorp/vault:1.21.4
        imagePullPolicy: {{ .Values.vault.image.pullPolicy }} 
        ports:
        - name: http 
          containerPort: {{ .Values.vault.app.port }}
        {{- if .Values.resourcesEnabled }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- end }} 
        command: ["/bin/vault"]
        args:
          - "server"
          - "-config=/vault/config/vault.hcl"
{{- if .Values.vault.app.env }}
        envFrom:
        - configMapRef:
            name: {{ .Values.vault.app.name }}-configmap
{{- end }}
{{- if or .Values.vault.app.configfile .Values.vault.persistence.enabled }}
        volumeMounts:
        {{- if .Values.vault.app.configfile }}
        - name: {{ .Values.vault.app.name }}-configfilevolume
          mountPath: /vault/config/vault.hcl
          subPath: vault.hcl
        {{- end }}
        {{- if .Values.vault.persistence.enabled }}
        - name: {{ .Values.vault.app.name }}-volumedata
          mountPath: {{ .Values.vault.persistence.mountpath | quote }}
        {{- end }}
      volumes:
        {{- if .Values.vault.app.configfile }}
        - name: {{ .Values.vault.app.name }}-configfilevolume
          configMap: 
            name: {{ .Values.vault.app.name }}-configfilemap
        {{- end }}
        {{- if .Values.vault.persistence.enabled }}
        - name: {{ .Values.vault.app.name }}-volumedata
          persistentVolumeClaim:
            claimName: {{ .Values.vault.app.name }}-pvc
        {{- end }}
{{- end }}

