{{- if and .Values.image.privateRegistry.enabled (not .Values.image.privateRegistry.global) }}
{{- $ns := include "drm.namespace" . -}}
# Image pull secret built from the IDT registry credentials (icekube/idtsecret)
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drm.imagePullSecretName" . }}
  namespace: {{ $ns }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}
