{{- $ns := include "drm.namespace" . -}}
{{- range $org := list "org0" "org1" "org2" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-{{ $org }}
  namespace: {{ $ns }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.global.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.global.storageSize }}
{{- end }}
