{{- if .Values.ds2dataplane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ds2dataplane.app.name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
