apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ds2controlplane.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ds2controlplane.app.name }}  
    service: {{ .Values.ds2controlplane.app.name }} 
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8081
    name: management
    targetPort: 8081
  - port: 8082
    name: protocol
    targetPort: 8082
  - port: 8083
    name: control
    targetPort: 8083
  - port: 8084
    name: catalog
    targetPort: 8084
  type: ClusterIP
  selector:
    app: {{ .Values.ds2controlplane.app.name }}

