apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ds2dataplane.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ds2dataplane.app.name }}  
    service: {{ .Values.ds2dataplane.app.name }} 
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 8080
  - port: 8083
    name: control
    targetPort: 8083
  - port: 11002
    name: public
    targetPort: 11002
  - port: 1044
    name: undefined
    targetPort: 1044
  type: ClusterIP
  selector:
    app: {{ .Values.ds2dataplane.app.name }}

