{{- if .Values.ds2identityhub.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ds2identityhub.app.name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- end }}
